name: GPT Translate per Commit
 
on:
  push:
    paths:
      - README.md
      - .github/**
      - _config.yml
      - _sass/color_schemes/wider.scss
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  gpt_translate:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository with two latest commits
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
 
      - name: Run GPT Translate
        uses: 3ru/gpt-translate@master
        with:
          model: "gpt-4"
          apikey: ${{ secrets.OPENAI_API_KEY }}
          inputFiles: './README.md'
          outputFiles: 'DE/*.md FR/*.md CH/*.md PL/*.md JA/*.md ES/*.md'
          languages: 'German French Mandarin Polish Japanese Spanish'